### ISSUE TITLE
Colors are messed up

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/mslearn-dotnetmaui-use-shared-resources#1]
The standard tip calculator in exercise 1 has some color issues. This is what it looks like for me.

![tip-calc](https://user-images.githubusercontent.com/1784452/182222493-c6c65b66-3a52-4168-978b-551cdfcb9197.png)

It seems like the resource dictionaries are being completely ignored. I created a new MAUI app and the colors are all correct.

VS 17.3.0 Preview 2.0

**Comment by MisinformedDNA** [comment]
Oh... it's because some of the settings are being picked from the Windows theme and other parts are not.

When Windows is in dark mode, the background of the buttons is white, but the style of the individual buttons tell the text to also be white.

When I switch Windows to light mode, everything looks good. This should be fixed to work with dark mode.

**Comment by ghost** [comment]
Same, hope it gets fixed

**Comment by jamesmontemagno** [comment]
I will be adjusting this to always default to light for the module.

**Comment by jamesmontemagno** [comment]
Fixed now
